# Generated by Django 3.2.9 on 2021-11-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delphius', '0002_employee_new_lead_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=200, null=True)),
                ('Lastname', models.CharField(max_length=200, null=True)),
                ('UserEmail', models.EmailField(max_length=200, null=True)),
            ],
        ),
    ]
