# Generated by Django 3.2.9 on 2021-12-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delphius', '0003_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_lead',
            name='latitude',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='new_lead',
            name='lead_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='new_lead',
            name='longitude',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
