# Generated by Django 3.2.9 on 2021-12-02 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delphius', '0004_auto_20211201_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(null=True)),
                ('expected', models.DateTimeField(null=True)),
                ('verified', models.DateTimeField(null=True)),
                ('action', models.DateTimeField(null=True)),
                ('site', models.CharField(max_length=200, null=True)),
                ('cont_person', models.CharField(max_length=200, null=True)),
                ('cont_no', models.CharField(max_length=13, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('region', models.CharField(max_length=200, null=True)),
                ('latitude', models.CharField(max_length=200, null=True)),
                ('longitude', models.CharField(max_length=200, null=True)),
                ('lead_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delphius.employee')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delphius.status')),
            ],
        ),
    ]
