# Generated by Django 3.2.9 on 2021-12-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delphius', '0006_interest_months_municipality_new_validation_operator_public_p_public_pr_shareable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Municipality',
            new_name='Dawn_Dusk',
        ),
        migrations.RenameModel(
            old_name='Months',
            new_name='DCI',
        ),
        migrations.RenameModel(
            old_name='Interest',
            new_name='MAR',
        ),
        migrations.RenameModel(
            old_name='Operator',
            new_name='OI',
        ),
        migrations.RenameModel(
            old_name='Public_P',
            new_name='PPL',
        ),
        migrations.RenameModel(
            old_name='Shareable',
            new_name='PPR',
        ),
        migrations.RenameModel(
            old_name='Public_PR',
            new_name='SS',
        ),
        migrations.RenameField(
            model_name='new_validation',
            old_name='municapal_approval',
            new_name='dawn_dusk',
        ),
        migrations.RenameField(
            model_name='new_validation',
            old_name='dusk_dawn',
            new_name='dci',
        ),
        migrations.RenameField(
            model_name='new_validation',
            old_name='duration_ppr',
            new_name='esc',
        ),
        migrations.RenameField(
            model_name='new_validation',
            old_name='power_connection',
            new_name='est_duration',
        ),
        migrations.RenameField(
            model_name='new_validation',
            old_name='del_connect_interest',
            new_name='mar',
        ),
        migrations.RenameField(
            model_name='new_validation',
            old_name='Operator_interest',
            new_name='oi',
        ),
        migrations.RenameField(
            model_name='new_validation',
            old_name='solution',
            new_name='pce',
        ),
        migrations.RenameField(
            model_name='new_validation',
            old_name='public_p',
            new_name='ppl',
        ),
        migrations.RenameField(
            model_name='new_validation',
            old_name='solution_share',
            new_name='ppr',
        ),
        migrations.RenameField(
            model_name='new_validation',
            old_name='public_pr',
            new_name='ss',
        ),
        migrations.RemoveField(
            model_name='new_validation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='new_validation',
            name='date_created',
        ),
        migrations.AddField(
            model_name='new_validation',
            name='solution_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='new_validation',
            name='cont_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
